import React, { createContext, useContext, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, NavLink, Navigate, Route, Routes, useNavigate } from 'react-router-dom';
import axios from 'axios';
import { Bell, Bookmark, Compass, Heart, Home, Image, LogOut, MessageCircle, Plus, Search, Send, UserRound } from 'lucide-react';
import './styles.css';
const api = axios.create({ baseURL: import.meta.env.VITE_API_URL || 'http://localhost:5000/api' });
const Auth = createContext(); const useAuth = () => useContext(Auth);
const avatar = (user) => user?.avatar || `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent(user?.name || user?.username || 'P')}&backgroundColor=ff5c5c`;
function AuthProvider({ children }) { const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('pulse_user') || 'null')); const [token, setToken] = useState(() => localStorage.getItem('pulse_token')); useEffect(() => { if (token) api.defaults.headers.common.Authorization = `Bearer ${token}`; }, [token]); const login = (data) => { setUser(data.user); setToken(data.token); localStorage.setItem('pulse_user', JSON.stringify(data.user)); localStorage.setItem('pulse_token', data.token); }; const logout = () => { setUser(null); setToken(null); localStorage.clear(); }; return <Auth.Provider value={{ user, setUser, login, logout }}>{children}</Auth.Provider>; }
function Shell({ children }) { const { user, logout } = useAuth(); const links = [[Home, 'Home', '/'], [Compass, 'Explore', '/explore'], [MessageCircle, 'Messages', '/messages'], [Bell, 'Activity', '/activity'], [Bookmark, 'Saved', '/saved']]; return <main className="layout"><aside className="sidebar"><NavLink className="brand" to="/">pulse<span>.</span></NavLink><nav>{links.map(([Icon, label, to]) => <NavLink key={to} to={to}><Icon size={21}/><span>{label}</span></NavLink>)}</nav><NavLink to="/create" className="create"><Plus size={20}/>Create</NavLink><div className="account"><img src={avatar(user)}/><div><strong>{user?.name}</strong><small>@{user?.username}</small></div><button title="Sign out" onClick={logout}><LogOut size={18}/></button></div></aside><section className="content">{children}</section></main>; }
function AuthPage() { const { login } = useAuth(); const navigate = useNavigate(); const [mode, setMode] = useState('login'); const [form, setForm] = useState({ name: '', username: '', email: '', password: '' }); const [error, setError] = useState(''); const submit = async (e) => { e.preventDefault(); try { const { data } = await api.post(`/auth/${mode === 'login' ? 'login' : 'register'}`, form); login(data); navigate('/'); } catch (e) { setError(e.response?.data?.message || 'Something went wrong'); } }; return <div className="auth"><div className="auth-art"><p>REAL PEOPLE. REAL MOMENTS.</p><h1>Find your<br/>people.</h1><span>Share what moves you. Keep up with the people who matter.</span></div><form onSubmit={submit}><div className="brand">pulse<span>.</span></div><h2>{mode === 'login' ? 'Welcome back' : 'Join the conversation'}</h2><p>{mode === 'login' ? 'Enter your details to continue.' : 'Create your free Pulse account.'}</p>{mode === 'register' && <><input placeholder="Full name" required onChange={(e) => setForm({...form, name:e.target.value})}/><input placeholder="Username" required onChange={(e) => setForm({...form, username:e.target.value})}/></>}<input type="email" placeholder="Email address" required onChange={(e) => setForm({...form, email:e.target.value})}/><input type="password" placeholder="Password" minLength="6" required onChange={(e) => setForm({...form, password:e.target.value})}/>{error && <em>{error}</em>}<button className="primary">{mode === 'login' ? 'Sign in' : 'Create account'}</button><button type="button" className="text-button" onClick={() => setMode(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'New here? Create an account' : 'Already have an account? Sign in'}</button></form></div>; }
function PostCard({ post, onChange }) { const { user } = useAuth(); const [comment, setComment] = useState(''); const liked = post.likes?.some((id) => (id._id || id) === user.id); const like = async () => { const { data } = await api.post(`/posts/${post._id}/like`); onChange({...post, likes: data.likes}); }; const addComment = async (e) => { e.preventDefault(); if (!comment.trim()) return; const {data} = await api.post(`/posts/${post._id}/comments`, {text: comment}); onChange(data); setComment(''); }; return <article className="post"><header><img src={avatar(post.author)}/><div><strong>{post.author.name}</strong><small>@{post.author.username} · {new Date(post.createdAt).toLocaleDateString()}</small></div><button className="dots">•••</button></header><p className="caption">{post.caption}</p>{post.mediaUrl && (post.mediaType === 'video' ? <video controls src={post.mediaUrl}/> : <img className="media" src={post.mediaUrl}/>) }<div className="actions"><button className={liked ? 'liked' : ''} onClick={like}><Heart fill={liked ? 'currentColor' : 'none'}/>{post.likes?.length || 0}</button><button><MessageCircle/>{post.comments?.length || 0}</button><button><Send/></button><button className="save"><Bookmark/></button></div>{post.comments?.slice(-2).map((c) => <p className="comment" key={c._id}><strong>{c.author?.username || 'member'}</strong> {c.text}</p>)}<form className="comment-form" onSubmit={addComment}><input value={comment} onChange={(e) => setComment(e.target.value)} placeholder="Add a comment…"/><button>Post</button></form></article>; }
function Feed({ explore = false }) { const [posts, setPosts] = useState([]); const [suggestions, setSuggestions] = useState([]); const load = async () => { const [{data: p}, {data: s}] = await Promise.all([api.get(`/posts/${explore ? 'explore' : 'feed'}`), api.get('/users/suggestions')]); setPosts(p); setSuggestions(s); }; useEffect(() => { load(); }, [explore]); const follow = async (id) => { await api.post(`/users/${id}/follow`); setSuggestions(suggestions.filter((x) => x._id !== id)); }; return <Shell><div className="feed"><div className="feed-head"><div><p className="eyebrow">{explore ? 'DISCOVER' : 'YOUR SPACE'}</p><h1>{explore ? 'Explore what’s fresh' : 'Good morning.'}</h1></div><NavLink to="/create" className="round-create"><Plus/></NavLink></div>{!posts.length && <div className="empty"><Image/><h3>{explore ? 'Nothing to explore yet' : 'Your feed is waiting'}</h3><p>Follow people or share your first moment to bring it to life.</p><NavLink to="/explore">Discover creators</NavLink></div>}{posts.map((post) => <PostCard key={post._id} post={post} onChange={(changed) => setPosts(posts.map((p) => p._id === changed._id ? changed : p))}/>)}</div><aside className="rightbar"><div className="search"><Search size={18}/><input placeholder="Search Pulse"/></div><section><p className="eyebrow">PEOPLE TO FOLLOW</p>{suggestions.map((person) => <div className="suggestion" key={person._id}><img src={avatar(person)}/><div><strong>{person.name}</strong><small>@{person.username}</small></div><button onClick={() => follow(person._id)}>Follow</button></div>)}</section><footer>© 2026 Pulse · Built for connection</footer></aside></Shell>; }
function Create() { const navigate = useNavigate(); const [form, setForm] = useState({ caption:'', mediaUrl:'', mediaType:'image' }); const [loading, setLoading] = useState(false); const submit = async (e) => {e.preventDefault(); setLoading(true); await api.post('/posts', {...form, mediaType: form.mediaUrl ? form.mediaType : 'none'}); navigate('/');}; return <Shell><div className="create-page"><p className="eyebrow">NEW POST</p><h1>Share a moment</h1><form onSubmit={submit}><textarea autoFocus placeholder="What’s on your mind?" maxLength="500" onChange={(e) => setForm({...form,caption:e.target.value})}/><label>Media URL <input placeholder="https://…" onChange={(e) => setForm({...form, mediaUrl:e.target.value})}/></label><div className="selects"><label>Type <select onChange={(e) => setForm({...form,mediaType:e.target.value})}><option value="image">Image</option><option value="video">Video</option></select></label><button className="primary" disabled={loading}>{loading ? 'Publishing…' : 'Publish post'}</button></div></form></div></Shell>; }
function Placeholder({ icon: Icon, title, text }) { return <Shell><div className="placeholder"><Icon size={42}/><h1>{title}</h1><p>{text}</p></div></Shell>; }
function App() { const {user} = useAuth(); return <Routes>{!user ? <Route path="*" element={<AuthPage/>}/> : <><Route path="/" element={<Feed/>}/><Route path="/explore" element={<Feed explore/>}/><Route path="/create" element={<Create/>}/><Route path="/messages" element={<Placeholder icon={MessageCircle} title="Messages" text="Your conversations will appear here."/>}/><Route path="/activity" element={<Placeholder icon={Bell} title="Activity" text="Likes, follows and comments will show up here."/>}/><Route path="/saved" element={<Placeholder icon={Bookmark} title="Saved posts" text="Save posts to revisit them later."/>}/><Route path="*" element={<Navigate to="/"/>}/></>}</Routes>; }
createRoot(document.getElementById('root')).render(<BrowserRouter><AuthProvider><App/></AuthProvider></BrowserRouter>);
