import React, { createContext, useContext, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, NavLink, Navigate, Route, Routes, useNavigate } from 'react-router-dom';
import { Bell, Bookmark, Compass, Heart, Home, ImagePlus, LogOut, Menu, MessageCircle, MoreHorizontal, Plus, Search, Send, Settings, UserRound } from 'lucide-react';
import './styles.css';

const people = [
  { id: 'maya', name: 'Maya Chen', username: 'mayachen', avatar: 'https://i.pravatar.cc/150?img=47', bio: 'Designing a slower, more beautiful internet.', following: true },
  { id: 'leo', name: 'Leo Martins', username: 'leomakes', avatar: 'https://i.pravatar.cc/150?img=12', bio: 'Film, food and finding the light.', following: false },
  { id: 'nora', name: 'Nora Bell', username: 'norabell', avatar: 'https://i.pravatar.cc/150?img=32', bio: 'Notes from the road.', following: true },
  { id: 'sam', name: 'Sam Rivera', username: 'samrivera', avatar: 'https://i.pravatar.cc/150?img=68', bio: 'Objects with a past life.', following: false },
  { id: 'jules', name: 'Jules Park', username: 'julespark', avatar: 'https://i.pravatar.cc/150?img=5', bio: 'Kitchen experiments + tiny joys.', following: false }
];
const currentUser = { id: 'you', name: 'Alex Morgan', username: 'alexmorgan', avatar: 'https://i.pravatar.cc/150?img=11', bio: 'Collecting little moments.', following: true };
const initialPosts = [
  { id: 1, author: people[0], caption: 'A quiet corner, a good book, and nowhere else to be.', image: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=1000&q=85', likes: 284, comments: [{ author: people[1], text: 'This is my kind of afternoon.' }], liked: false, saved: true, time: '2h' },
  { id: 2, author: people[1], caption: 'The city after rain always feels like a fresh start.', image: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=1000&q=85', likes: 613, comments: [{ author: people[3], text: 'The reflections are perfect.' }, { author: people[2], text: 'Need to visit soon.' }], liked: true, saved: false, time: '5h' },
  { id: 3, author: people[2], caption: 'Postcard from a place I want to remember exactly like this.', image: 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1000&q=85', likes: 927, comments: [], liked: false, saved: false, time: '1d' }
];

const AppContext = createContext(null);
const useApp = () => useContext(AppContext);
function AppProvider({ children }) {
  const [posts, setPosts] = useState(initialPosts);
  const [following, setFollowing] = useState(people.filter((person) => person.following).map((person) => person.id));
  const [isLoggedIn, setIsLoggedIn] = useState(true);
  const toggleLike = (id) => setPosts((items) => items.map((post) => post.id === id ? { ...post, liked: !post.liked, likes: post.likes + (post.liked ? -1 : 1) } : post));
  const toggleSave = (id) => setPosts((items) => items.map((post) => post.id === id ? { ...post, saved: !post.saved } : post));
  const addComment = (id, text) => setPosts((items) => items.map((post) => post.id === id ? { ...post, comments: [...post.comments, { author: currentUser, text }] } : post));
  const toggleFollow = (id) => setFollowing((ids) => ids.includes(id) ? ids.filter((item) => item !== id) : [...ids, id]);
  const addPost = ({ caption, image }) => setPosts((items) => [{ id: Date.now(), author: currentUser, caption, image, likes: 0, comments: [], liked: false, saved: false, time: 'now' }, ...items]);
  return <AppContext.Provider value={{ posts, following, toggleLike, toggleSave, addComment, toggleFollow, addPost, currentUser, isLoggedIn, setIsLoggedIn }}>{children}</AppContext.Provider>;
}
function Avatar({ person, size = 'normal' }) { return <img className={`avatar ${size}`} src={person.avatar} alt={person.name} />; }
function Brand() { return <NavLink className="brand" to="/">frame<span>.</span></NavLink>; }
function Layout({ children }) {
  const { currentUser, setIsLoggedIn } = useApp();
  const links = [[Home, 'Home', '/'], [Compass, 'Discover', '/discover'], [MessageCircle, 'Messages', '/messages'], [Bell, 'Activity', '/activity'], [Bookmark, 'Saved', '/saved']];
  return <div className="app-shell"><aside className="sidebar"><Brand /><nav className="main-nav">{links.map(([Icon, label, to]) => <NavLink key={to} end={to === '/'} to={to}><Icon size={21} strokeWidth={1.8} /><span>{label}</span></NavLink>)}</nav><NavLink to="/create" className="new-post"><Plus size={19} /> New post</NavLink><div className="sidebar-bottom"><NavLink to="/profile" className="profile-link"><Avatar person={currentUser} size="small" /><span><strong>{currentUser.name}</strong><small>@{currentUser.username}</small></span></NavLink><button className="icon-button" title="Sign out" onClick={() => setIsLoggedIn(false)}><LogOut size={18} /></button></div></aside><main className="main-content">{children}</main><MobileNav links={links} /></div>;
}
function MobileNav({ links }) { return <nav className="mobile-nav">{links.slice(0, 4).map(([Icon, label, to]) => <NavLink key={to} end={to === '/'} to={to}><Icon size={21} /><span>{label}</span></NavLink>)}<NavLink to="/profile"><UserRound size={21} /><span>Profile</span></NavLink></nav>; }
function Stories() { const stories = [currentUser, ...people]; return <section className="stories">{stories.map((person, index) => <button className="story" key={person.id}><span className={index === 0 ? 'story-ring own' : 'story-ring'}><Avatar person={person} /></span><span>{index === 0 ? 'Your story' : person.username}</span></button>)}</section>; }
function PostCard({ post }) {
  const { toggleLike, toggleSave, addComment } = useApp();
  const [comment, setComment] = useState('');
  const submitComment = (event) => { event.preventDefault(); if (comment.trim()) { addComment(post.id, comment.trim()); setComment(''); } };
  return <article className="post-card"><header className="post-header"><Avatar person={post.author} /><div><strong>{post.author.name}</strong><small>@{post.author.username} · {post.time}</small></div><button className="icon-button post-more" title="More options"><MoreHorizontal size={21} /></button></header><img className="post-image" src={post.image} alt={post.caption} /><div className="post-body"><div className="post-actions"><div><button className={post.liked ? 'action liked' : 'action'} onClick={() => toggleLike(post.id)} title="Like"><Heart size={23} fill={post.liked ? 'currentColor' : 'none'} /></button><button className="action" title="Comment"><MessageCircle size={23} /></button><button className="action" title="Share"><Send size={22} /></button></div><button className={post.saved ? 'action saved' : 'action'} onClick={() => toggleSave(post.id)} title="Save"><Bookmark size={23} fill={post.saved ? 'currentColor' : 'none'} /></button></div><strong className="like-count">{post.likes.toLocaleString()} likes</strong><p className="caption"><strong>{post.author.username}</strong> {post.caption}</p>{post.comments.slice(-2).map((comment, index) => <p className="comment" key={`${comment.text}-${index}`}><strong>{comment.author.username}</strong> {comment.text}</p>)}<form className="comment-form" onSubmit={submitComment}><input value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Add a comment..." /><button>Post</button></form></div></article>;
}
function RightRail() { const { following, toggleFollow } = useApp(); const suggestions = people.filter((person) => !following.includes(person.id)); return <aside className="right-rail"><div className="profile-summary"><Avatar person={currentUser} size="large" /><div><strong>{currentUser.name}</strong><span>@{currentUser.username}</span></div><button>Switch</button></div><div className="rail-heading"><span>Suggested for you</span><button>See all</button></div>{suggestions.slice(0, 4).map((person) => <div className="suggested" key={person.id}><Avatar person={person} size="small" /><div><strong>{person.username}</strong><small>Suggested for you</small></div><button onClick={() => toggleFollow(person.id)}>Follow</button></div>)}<footer>About · Help · Privacy · Terms<br /><span>© 2026 FRAME</span></footer></aside>; }
function HomePage() { const { posts } = useApp(); return <Layout><div className="page-grid"><section className="feed-column"><div className="topbar"><Brand /><div className="mobile-actions"><Search size={20} /><Menu size={22} /></div></div><Stories /><div className="feed-tabs"><button className="active">For you</button><button>Following</button></div>{posts.map((post) => <PostCard post={post} key={post.id} />)}</section><RightRail /></div></Layout>; }
function Discover() { const { posts } = useApp(); return <Layout><div className="discover-page"><div className="page-heading"><div><p className="eyebrow">DISCOVER</p><h1>Find your next favorite thing.</h1></div><div className="discover-search"><Search size={18} /><input placeholder="Search people or posts" /></div></div><div className="discover-grid">{[...posts, ...posts].map((post, index) => <button className={`discover-tile tile-${index % 5}`} key={`${post.id}-${index}`}><img src={post.image} alt={post.caption} /><span><Heart size={16} fill="white" /> {post.likes}</span></button>)}</div></div></Layout>; }
function Create() { const navigate = useNavigate(); const { addPost } = useApp(); const [form, setForm] = useState({ caption: '', image: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1000&q=85' }); const submit = (event) => { event.preventDefault(); if (!form.caption.trim()) return; addPost(form); navigate('/'); }; return <Layout><div className="create-page"><p className="eyebrow">NEW POST</p><h1>Share a moment.</h1><p className="subheading">Put something good into the world.</p><form className="create-form" onSubmit={submit}><div className="preview"><img src={form.image} alt="Post preview" /><div><ImagePlus size={23} /><span>Preview image</span></div></div><input value={form.image} onChange={(event) => setForm({ ...form, image: event.target.value })} placeholder="Paste an image URL" /><textarea value={form.caption} onChange={(event) => setForm({ ...form, caption: event.target.value })} placeholder="Write a caption..." maxLength="220" autoFocus /><div className="form-footer"><span>{form.caption.length}/220</span><button className="primary-button" type="submit">Publish post <Send size={16} /></button></div></form></div></Layout>; }
function Profile() { const { posts, following } = useApp(); const ownPosts = posts.filter((post) => post.author.id === currentUser.id); return <Layout><div className="profile-page"><div className="profile-cover"></div><div className="profile-info"><Avatar person={currentUser} size="profile" /><div className="profile-copy"><div className="profile-title"><div><h1>{currentUser.name}</h1><span>@{currentUser.username}</span></div><button className="outline-button"><Settings size={16} /> Edit profile</button></div><p>{currentUser.bio}</p><div className="stats"><span><strong>{ownPosts.length || 12}</strong> posts</span><span><strong>1,248</strong> followers</span><span><strong>{following.length}</strong> following</span></div></div></div><div className="profile-tabs"><button className="active">Posts</button><button>Saved</button><button>Tagged</button></div><div className="profile-grid">{(ownPosts.length ? ownPosts : posts).map((post) => <img key={post.id} src={post.image} alt={post.caption} />)}</div></div></Layout>; }
function SimplePage({ type }) { const data = { messages: ['Messages', 'Keep the conversation going.', MessageCircle], activity: ['Activity', 'Your likes, follows and comments will show up here.', Bell], saved: ['Saved posts', 'Posts you save will appear here.', Bookmark] }[type]; const Icon = data[2]; return <Layout><div className="simple-page"><div className="simple-icon"><Icon size={30} /></div><h1>{data[0]}</h1><p>{data[1]}</p>{type === 'messages' && <button className="primary-button"><Plus size={17} /> Start a conversation</button>}</div></Layout>; }
function AuthPage() { const { setIsLoggedIn } = useApp(); const [mode, setMode] = useState('login'); return <div className="auth-page"><div className="auth-visual"><Brand /><div><p className="eyebrow">A place for your moments</p><h1>Keep the good<br /><em>stuff</em> close.</h1><p>Share the details that make an ordinary day feel like yours.</p></div><span className="visual-note">Stories worth keeping.</span></div><form className="auth-form" onSubmit={(event) => { event.preventDefault(); setIsLoggedIn(true); }}><Brand /><h2>{mode === 'login' ? 'Welcome back' : 'Create your account'}</h2><p>{mode === 'login' ? 'Sign in to see what your people are up to.' : 'Join a thoughtful corner of the internet.'}</p>{mode === 'register' && <input required placeholder="Full name" />}{mode === 'register' && <input required placeholder="Username" />}<input required type="email" placeholder="Email address" /><input required type="password" placeholder="Password" /><button className="primary-button" type="submit">{mode === 'login' ? 'Sign in' : 'Create account'}</button><button className="switch-auth" type="button" onClick={() => setMode(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'New here? Create an account' : 'Already have an account? Sign in'}</button><small className="demo-note">Demo mode · no account or database required</small></form></div>; }
function App() { const { isLoggedIn } = useApp(); return isLoggedIn ? <Routes><Route path="/" element={<HomePage />} /><Route path="/discover" element={<Discover />} /><Route path="/create" element={<Create />} /><Route path="/profile" element={<Profile />} /><Route path="/messages" element={<SimplePage type="messages" />} /><Route path="/activity" element={<SimplePage type="activity" />} /><Route path="/saved" element={<SimplePage type="saved" />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes> : <Routes><Route path="*" element={<AuthPage />} /></Routes>; }
createRoot(document.getElementById('root')).render(<BrowserRouter><AppProvider><App /></AppProvider></BrowserRouter>);
